CONFIG_ARCH_POSIX_TRAP_ON_FATAL=y
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_FRAME_POINTER=y
CONFIG_ASAN=y
CONFIG_UBSAN=y
# CONFIG_MSAN=y
CONFIG_STACK_USAGE=y
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_THREAD_INFO=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_OUTPUT_SYMBOLS=y
CONFIG_OUTPUT_DISASSEMBLY=y