CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=1000000
# CONFIG_FPU=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y
CONFIG_REBOOT=y
# CONFIG_FPU_SHARING=y
CONFIG_FLASH=y
# CONFIG_DISPLAY=y
# CONFIG_SDL_DISPLAY_DEFAULT_PIXEL_FORMAT_MONO01=y
# CONFIG_FLASH_SHELL=y
# CONFIG_FLASH_SHELL_TEST_COMMANDS=y
# CONFIG_GPIO_SHELL=y
# CONFIG_UART_SHELL=y
# CONFIG_SHELL=y
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_POSIX_API=y
# CONFIG_POSIX_C_LIB_EXT=y
# CONFIG_GETOPT_LONG=y
# CONFIG_SHELL_GETOPT=y
CONFIG_SERIAL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
# CONFIG_LOG_FRONTEND=y
# CONFIG_LOG_THREAD_ID_PREFIX=y
# CONFIG_LOG_INFO_COLOR_GREEN=y
# CONFIG_LOG_DBG_COLOR_BLUE=y
# CONFIG_LOG_BACKEND_UART=y
# CONFIG_LOG_CMDS=y
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_CLIENT=y
CONFIG_MODBUS_SERIAL=y
# CONFIG_NETWORKING=y
# CONFIG_NET_L2_WIFI_SHELL=y
# CONFIG_NET_IPV4=y
# CONFIG_NET_SHELL=y
# CONFIG_NET_DHCPV4=y
# CONFIG_NET_DHCPV6=y
# CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_SHELL=y
CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_CHANNEL_ID=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y


CONFIG_PRINTK=y

# CONFIG_NETWORKING=y
# CONFIG_NET_IPV6=y
# CONFIG_NET_IPV4=y
# CONFIG_NET_ARP=y
# CONFIG_NET_UDP=y
# CONFIG_NET_TCP=y
# CONFIG_NET_L2_VIRTUAL=y
# CONFIG_NET_DHCPV4=n
# CONFIG_NET_CONNECTION_MANAGER=y
# CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=3
# CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=3
# CONFIG_NET_MAX_CONTEXTS=10
# CONFIG_NET_PKT_TX_COUNT=20
# CONFIG_NET_BUF_TX_COUNT=50

# CONFIG_TEST_RANDOM_GENERATOR=y

# CONFIG_INIT_STACKS=y

# CONFIG_NET_BUF_LOG=n
# CONFIG_NET_LOG=n
# CONFIG_QEMU_ICOUNT=y

# CONFIG_QEMU_ICOUNT_SHIFT=6

# # CONFIG_SERIAL=y
# # # CONFIG_SERIAL_SUPPORT_INTERRUPT=y
# # CONFIG_SERIAL_ESP32_USB=y

# CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
# CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.3"

# CONFIG_NET_SHELL=y
# CONFIG_KERNEL_SHELL=y
# CONFIG_SHELL_BACKEND_TELNET=y
# CONFIG_SHELL_TELNET_SUPPORT_COMMAND=y
# CONFIG_NET_TCP_LOG_LEVEL_DBG=y